### PR TITLE
Created new tutorials for the website

### PR DESCRIPTION
**Pull request by maugavilla**
Save the workspaces with the results, and loads then to create the tutorials. Saving the computing time when compiling the website

### CODE REVIEW

**Comment by ecmerkle** [comment]
Thanks, this looks really nice! One initial question: are the models in the RData files unusual, like they do not converge or take a long time to run? I am considering whether we instead want pkgdown to run the models and cache the results. This would have the advantage that, if some result or output changes in future versions of blavaan, the tutorials are automatically updated with the changes. I think we discussed this in the past but don't remember what we discussed.

**Comment by maugavilla** [comment]
No, these don't take long and are normal blavaan models. I haven't worked with the cache before. But sounds like a good idea, so it would only eun the models if something specific changes, instead of everytime it's compiled?

I will use the RData then in cases that take too long to run only then

**Comment by maugavilla** [comment]
Also, i think the check failed because i used the package brms for one of the tutorials. Didn't know how to tell it to be able to load it

**Comment by maugavilla** [comment]
I added the chache=T in the tutorials. Need to give pkgdown access to load brms for it to bulid the site

**Comment by ecmerkle** [comment]
Thanks, I will work on it soon!

**Pull request merged**
